In [ ]:
import numpy as np
import seaborn as sns
import pandas as pd

<font size='4' face='Times new Roman'>
    Dit worden de US Factors
    <font>

In [33]:
Predictors = pd.read_csv('/Users/sebasleen/Seminargroup/US Factors/PredictorLSretWide.csv')
Predictors

,date,AM,AOP,AbnormalAccruals,Accruals,AccrualsBM,Activism1,Activism2,AdExp,AgeIPO,...,retConglomerate,roaq,sfe,sinAlgo,skew1,std_turn,tang,zerotrade,zerotradeAlt1,zerotradeAlt12
0,1963-07-31,-1.556432,NaN,NaN,0.986994,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,-0.643640,NaN,-0.359161,-0.502932,0.660920,1.713943,1.640960
1,1963-08-30,-1.970184,NaN,NaN,2.906035,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,-1.118497,NaN,-2.977146,-0.415364,-5.901811,-5.347975,-3.741593
2,1963-09-30,0.417170,NaN,NaN,0.442702,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.713116,NaN,3.096587,3.265008,4.623936,4.122808,4.070821
3,1963-10-31,0.011723,NaN,NaN,1.926600,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,-2.690759,NaN,-4.302036,-0.773917,-4.487569,-2.302183,-3.085440
4,1963-11-29,0.546948,NaN,NaN,0.875763,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.996779,NaN,1.348050,1.779311,0.155358,-1.659265,-0.706777
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
673,2019-08-30,-3.477967,1.022858,-0.257870,-3.476139,-0.660723,NaN,NaN,-0.648690,-4.986503,...,4.478571,2.282955,1.182316,2.778965,1.230961,5.091798,0.396452,4.728797,5.058082,4.192077
674,2019-09-30,9.837431,1.138211,-1.426835,-0.879171,6.541993,NaN,NaN,6.826555,7.065012,...,0.040627,4.787744,10.712464,-3.575145,-3.073241,-10.305543,-8.314369,-3.140902,-2.567587,-3.336978
675,2019-10-31,-0.619649,-0.268992,2.529173,-3.231276,-3.229082,NaN,NaN,-0.637454,5.220963,...,2.446253,2.879307,3.347928,3.608734,2.450172,2.517805,0.721325,0.999582,1.315765,-0.457785
676,2019-11-29,-5.184910,-1.554425,1.479976,4.253688,-5.467083,NaN,NaN,-0.085064,-10.001974,...,3.103692,-4.107017,-3.390931,7.945822,0.028890,2.103129,1.086991,-0.639321,1.023264,-0.378260
677,2019-12-31,1.037594,0.215954,-2.188127,0.662900,-4.129853,NaN,NaN,0.950350,-9.463377,...,-3.823217,-6.937062,-10.548105,2.708733,2.726079,-6.652276,11.396096,-5.757521,-3.655052,-2.626997